### PR TITLE
Added support for Gree YT aircons

### PR DESCRIPTION
**Pull request by rob-deutsch**
This PR adds support for Gree YT aircons.

The early commits do a bit of "housekeeping" to clean up the Gree code a bit.

### CODE REVIEW

**Comment by ToniA** [comment]
Thank you :)

**Comment by marcinus66** [comment]
When GREE_YT will be available in ESPHOME arduino-libraries? How does it work?

I tried to use external library v 1.0.21 but ESPHOME spits out a compilation error (no "greeyt")

**Comment by rob-deutsch** [comment]
Good question! I've asked in #155 what the usual process is for publishing the library. When the library is published ESPHOME can then be modified to add support for greeyt.

**Comment by marcinus66** [comment]
Thanks... so let's wait for reply.

**Comment by ToniA** [comment]
I will push a new release out

**Comment by marcinus66** [comment]
how long should it take?

**Comment by ToniA** [comment]
I submitted 1.0.23 last week: https://registry.platformio.org/libraries/tonia/HeatpumpIR

**Comment by marcinus66** [comment]
And what does it look like with eshome? I checked a week ago and still couldn't select "gree_yt"...is there any eshome update needed?

**Comment by ToniA** [comment]
This should be done by the ESPHome community. I have no experience on ESPHome

**Comment by marcinus66** [comment]
I see. Thanks.

**Comment by rob-deutsch** [comment]
Hey @marcinus66 , thanks for the nudge, I'll push it through to esphome on the weekend.

**Comment by marcinus66** [comment]
Hey @rob-deutsch, I've been just told that I need to make a PR to bump the library version in esphome. But I am not familiar with this.. so please do the honors :-) thanks in advance!

**Comment by marcinus66** [comment]
Hello @rob-deutsch, any news with esphome issue?

**Comment by rob-deutsch** [comment]
I pushed it through last week, ahead of schedule, and it was accepted a few days ago. It's in the esphome `dev` branch now.

Lets try and keep this repository purely about `arduino-heatpumpir`, and discuss anything related to `esphome` in their repo.

https://github.com/esphome/esphome/pull/5269

**Comment by marcinus66** [comment]
sure... I will delete my inquires foe esphome... thx

**Pull request merged**
